# for manual testing / development

### Send POST request with body as parameters
POST http://localhost:8080/cinnamon/userAccount/createXml
ticket: b6437050-cd5c-49bd-8bb6-666b48aab095@demo
Content-Type: application/xml

<CreateUserAccountRequest>
<name>c6</name>
<fullname>Der Tester</fullname>
<password>no-password</password>
<loginType>CINNAMON</loginType>
<email>null@invalid</email>
<languageId>51</languageId>
<changeTracking>true</changeTracking>
</CreateUserAccountRequest>

###