# update link
POST http://localhost:8080/cinnamon/link/updateLink
ticket: b6437050-cd5c-49bd-8bb6-666b48aab095@demo
Content-Type: application/x-www-form-urlencoded

link_id=59494&object_id=59533

###

# delete link
POST http://localhost:8080/cinnamon/link/deleteLink
ticket: b6437050-cd5c-49bd-8bb6-666b48aab095@demo
Content-Type: application/x-www-form-urlencoded

link_id=59494

###