POST http://localhost:8080/cinnamon/osd/renderIndexedXml
ticket: b6437050-cd5c-49bd-8bb6-666b48aab095@demo
Content-Type: application/x-www-form-urlencoded

id=59533

###

POST http://localhost:8080/cinnamon/folder/renderIndexedXml
ticket: b6437050-cd5c-49bd-8bb6-666b48aab095@demo
Content-Type: application/x-www-form-urlencoded

id=59447

###